[XDebug]
xdebug.mode = debug
xdebug.client_enable = true
xdebug.client_host = {XDEBUG_CLIENT_HOST}
xdebug.client_port = 9003
xdebug.client_handler = dbgp
xdebug.scream = true
xdebug.idekey = {XDEBUG_IDE_KEY}
xdebug.log = {LOG_HOME}/xdebug.log
# PHPStorm
xdebug.file_link_format = 'javascript:var r = new XMLHttpRequest; r.open("get", "http://localhost:63342/api/file/%f:%l");r.send()'
# xdebug.use_compression=false
