CREATE DATABASE IF NOT EXISTS {DSN_NAME};

CREATE USER IF NOT EXISTS {DSN_USER}@'{DATABASE_NETWORK}' IDENTIFIED BY '{DSN_PASSWORD}';

GRANT ALL PRIVILEGES ON {DSN_NAME}.* TO {DSN_USER}@'{DATABASE_NETWORK}';

FLUSH PRIVILEGES;
